### ISSUE TITLE
Authors info

### ISSUE THREAD

**Issue by graciellehigino** [PoisotLab/ms_frontiers_kids#13]
## Bio and photo
- [x] @FrancisBanville biography and photo
- [x] @gabrieldansereau biography and photo
- [x] @graciellehigino biography and photo
- [ ] @Norma-Forero biography and photo
- [x] @tpoisot biography and photo

## Authors and Affiliations
"All names are listed together and separated by commas. Provide exact and correct author names as these will be indexed in official archives. Any change requests after publication will incur additional costs and will be solely at the author’s charge. Affiliations should be keyed to the author’s name with superscript numbers and be listed as follows: Laboratory, Institute, Department, Organization, City, State abbreviation, and Country (without detailed address information such as city zip codes or street names).
If one of the authors has a change of address, list the new address below the correspondence details using a superscript symbol and use the same symbol to indicate the author in the author list."

- [x] @FrancisBanville
- [x] @gabrieldansereau
- [x] @graciellehigino
- [x] @Norma-Forero
- [x] @tpoisot

**Comment by gabrieldansereau** [comment]
Following their template, the affiliation for the lab would be:

> Quantitative & Computational Ecology Laboratory, Département de sciences biologiques, Université de Montréal, Montréal, QC, Canada.

Should be the only one for me.

**Comment by FrancisBanville** [comment]
Same here!
