### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by graciellehigino** [PoisotLab/ms_frontiers_kids#9]
- [x] Brainstorm title options
- [x] Choose 2-3

**Comment by FrancisBanville** [comment]
1. Machines in search of life: where do animals and plants live?

**Comment by FrancisBanville** [comment]
2. Machines in search of life: a story of raccoons and other living creatures

**Comment by FrancisBanville** [comment]
3. Where do animals and plants live?

**Comment by FrancisBanville** [comment]
4. Finding where living creatures might live

**Comment by FrancisBanville** [comment]
5. When machines help humans find plants and animals

**Comment by FrancisBanville** [comment]
6. When machines help us find raccoons and other living creatures

**Comment by gabrieldansereau** [comment]
Aaaaand... "When machines help us find raccoons and other living creatures" wins!
